### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by evanplaice** [guybedford/markdown-component#1]
@guybedford Hi

This repo doesn't have a license. Do you have any problems with me cloning and extending it? 

I'm adapting the code to work as an Angular2 component that can be installed via JSPM.

**Comment by guybedford** [comment]
No problem at all, and thanks for asking. Do share what you come up with if you like.

**Comment by evanplaice** [comment]
Here it is:
https://github.com/evanplaice/ng2-markdown-component

Once I get a few more details sorted out, I'll add it to the registry.
